name       : gthumb
version    : 3.10.3
release    : 25
source     :
    - https://download.gnome.org/sources/gthumb/3.10/gthumb-3.10.3.tar.xz : dab73f77cc2963ebe90112972c301441d228af3003cfef3f8b7300a6d5d3c212
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Image viewer and browser utility
description: |
    gthumb is an application for viewing, editing, and organizing collections of images.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(colord)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(exiv2)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libbrasero-media3)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libssh)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
