name       : gthumb
version    : 3.6.0
release    : 7
source     :
    - https://download.gnome.org/sources/gthumb/3.6/gthumb-3.6.0.tar.xz : 48248bb0d3b2980d9d2ec20151d148f734e5f8c6798027b96a07bf6fb7af87fd
license    : GPL-2.0
component  : multimedia.graphics
summary    : Image viewer and browser utility
description: |
    gthumb is an application for viewing, editing, and organizing collections of images.
builddeps  :
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(exiv2)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libbrasero-media3)
    - pkgconfig(libjpeg)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
