name       : gthumb
version    : 3.6.1
release    : 10
source     :
    - https://download.gnome.org/sources/gthumb/3.6/gthumb-3.6.1.tar.xz : 9cabf9e17f8feab1012836f6371e32a555f030bd3c912a565dc49795f83342ee
license    : GPL-2.0
component  : multimedia.graphics
summary    : Image viewer and browser utility
description: |
    gthumb is an application for viewing, editing, and organizing collections of images.
builddeps  :
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(exiv2)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libbrasero-media3)
    - pkgconfig(libjpeg)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
