name       : gthumb
version    : 3.7.1
release    : 15
source     :
    - https://download.gnome.org/sources/gthumb/3.7/gthumb-3.7.1.tar.xz : 73bb657bb3151dc1ecc73bb73554fdc5fb6cdc96e1f21d9d47c4b6becf5ed5c0
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Image viewer and browser utility
description: |
    gthumb is an application for viewing, editing, and organizing collections of images.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(colord)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(exiv2)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libbrasero-media3)
    - pkgconfig(libjpeg)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
